# Generated by Django 4.1 on 2022-11-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=100)),
                ('buy_price', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifted_diys', to='characters.villager')),
            ],
        ),
    ]
